---
name: Run CI on push
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  golangci-lint:
    strategy:
      matrix:
        go:
          - "1.20"
          - "1.21"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  tests:
    strategy:
      matrix:
        go:
          - "1.20"
          - "1.21"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: make test
